# Generated by Django 4.0.5 on 2022-07-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_books_photo_author_alter_books_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='photo_book',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
